### ISSUE TITLE
generated start scripts get "destroyed"

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle-java-modules#11]
You manipulate the generated start scripts and thereby destroy their line endings.
The windows start script must have windows style line endings, the unix start script must have unix style line endings.
With your code, you read in all lines of the scripts and then write it out with the current platform line ending.
This either destroys the line endings of the windows start script if you build on *nix or the line endings of the unix start script if you build on Windows.
You must save the start scripts with the correct line ending.
If you don't want to hard-code them, you can use `org.gradle.util.TextUtil.getWindowsLineSeparator()` and `org.gradle.util.TextUtil.getUnixLineSeparator()`.
Or you could maybe just read the whole file into one String, do the replace on the whole String and then write out the String to the file again.
Would also be more performant, as it doesn't make too much sense to do the replace on each line.
Besides that in this case you should pre-compile the regex instead of using `String#replaceFirst` which requires to compile the regex for each and every single line and thus cost pretty much performance.

**Comment by rgoldberg** [comment]
If this issue is implemented in Gradle core (gradle/gradle#6239), then the plugin wouldn't need to rewrite the generated starts scripts, thereby fixing both the line separator and performance problems.

**Comment by jjohannes** [comment]
Java Modules, and start script generation for modules, is supported by Gradle 6.4 directly.
