### ISSUE TITLE
Compile modules exporting packages that have no Java source, but have other JVM source

### ISSUE THREAD

**Issue by rgoldberg** [gradle/gradle-java-modules#20]
Allow compiling modules with a `module-info.java` that exports a package that has no Java source, but that has source in another JVM language (like Kotlin) in the same build.

Should be achieved by using `--patch-module` instead of `--module-path` for the outputs of source sets in the same build that are in `JavaCompile#classpath`.

**Comment by jjohannes** [comment]
Gradle 6.4 now has Module support built-in. Please open an issue on https://github.com/gradle/gradle for this use case and how you wound imagine this to work in Gradle.

You can already do it by adding --patch-module arguments to the corresponding compile/run/test tasks - e.g.: 

```
tasks.compileJava {
    // this is needed because we have a separate compile step in this example with the 'module-info.java' is in 'main/java' and the Kotlin code is in 'main/kotlin'
    options.compilerArgs = listOf("--patch-module", "org.module.kotlin=${sourceSets.main.get().output.asPath}")
}
```
