### ISSUE TITLE
Configure Tasks by type instead of only specific named Tasks

### ISSUE THREAD

**Issue by rgoldberg** [gradle/gradle-java-modules#24]
Configure `Task`s by type (e.g., `JavaCompile`, `JavaExec`) instead of only specific named `Task`s (e.g., `"compileJava"`, `"run"`).

This will enable module usage for all source sets, all java executions, etc.

**Comment by jjohannes** [comment]
This is not an issue anymore with the Module support in Gradle 6.4+.
