### ISSUE TITLE
Support multiple modules per SourceSet / Task / JavaCompile

### ISSUE THREAD

**Issue by rgoldberg** [gradle/gradle-java-modules#25]
Support multiple modules per SourceSet / Task

Support multiple modules per `JavaCompile` by using `--module-source`

**Comment by jjohannes** [comment]
Gradle 6.4 now has Module support built-in. It does not have this feature, as we do not have a good use case for it.

Please open an issue on https://github.com/gradle/gradle describing the use case for this.
