### ISSUE TITLE
Rearchitect code base to easily optionally support additional tasks

### ISSUE THREAD

**Issue by rgoldberg** [gradle/gradle-java-modules#26]
Rearchitect code base to easily optionally support additional tasks, like `KotlinCompile`, `ScalaCompile`, etc., without downloading dependencies that are unnecessary for a build, and without errors.

Originally used a `ServiceLoader` SPI until @oehme mentioned it performs poorly & is brittle.

Ignore service providers that fail to load because their `Task` isn't in the Gradle class path (e.g., if the Kotlin plugin isn't applied, the `KotlinCompile` won't be in the class path, so the service provider for it will fail to load, which must not cause an error in Gradle).

**Comment by jjohannes** [comment]
Closing, as this plugin is no longer maintained.

Please open an issue on https://github.com/gradle/gradle for enhancement requests on the native Module support in Gradle 6.4+.
