### ISSUE TITLE
DSL for manual Jigsaw option setup

### ISSUE THREAD

**Issue by rgoldberg** [gradle/gradle-java-modules#28]
DSL for manual Jigsaw option setup possibly supporting:

1. supplying Jigsaw options
   - should only be necessary for options that must coordinate with Gradle properties like `Task#inputs`; otherwise, `String` arguments could be appended without a DSL for this plugin
   - even if not necessary, might be more pleasant to work with a DSL than `String` args

2. disabling certain auto-configuration by the plugin

**Comment by jjohannes** [comment]
Modules are supported directly by Gradle 6.4 now - if there is anything missing, pleas open an issue on https://github.com/gradle/gradle.
