### ISSUE TITLE
Make an `Automatic-Module-Name` entry if no `module-info.java`

### ISSUE THREAD

**Issue by eljobe** [gradle/gradle-java-modules#3]
Some projects might not be ready to become modules yet, but may want to reserve their module names for future development. The plugin should just add an `Automatic-Module-Name` entry for jar files and nothing else if there is no `module-info.class` when creating the jar.

**Comment by jodastephen** [comment]
The module name must be an explicit choice, and not derived from other pieces of information like the groupId/artifactId. This is because once out there it will get baked into other projects and be impossible to change.

**Comment by jjohannes** [comment]
Java Modules are now directly supported in Gradle 6.4 where this problem. The recommendation there is to put an automatic module name in the manifest directly by configuring the jar task (as derivation is not recommended).
