### ISSUE TITLE
Modify Tasks somewhere nicer than Task#doFirst {}

### ISSUE THREAD

**Issue by rgoldberg** [gradle/gradle-java-modules#30]
Modify `Task`s somewhere nicer than `Task#doFirst {}`.

There does not appear to be a better general way to properly configure every `Task` for Jigsaw, since the plugin must read from existing Gradle properties, some of which are modified in other `Action`s passed to `Task#doFirst {}`.

`CommandLineArgumentProvider` is not used by all tasks, and won't work for some of the `Task`s that do use it since we need to clear the `classpath` property, but, e.g., `JavaCompile` constructs the `-classpath` arg from `classpath` before the `CommandLineArgumentProvider`s are run.

Will probably require changes in Gradle core, so `Task#doFirst {}` is probably the safest option for now.

**Comment by jjohannes** [comment]
This should not be necessary anymore with the Module support in Gradle 6.4+.
