### ISSUE TITLE
Reset cleared properties in Task#doLast {}

### ISSUE THREAD

**Issue by rgoldberg** [gradle/gradle-java-modules#31]
Plugin clears some `Task` properties (e.g., `classpath` or the main class name) for many `Task`s in `Task#doFirst {}` so the properties won't be used during execution to generate arguments.

Probably should save the value of these properties before clearing them, and then later reset the properties to the saved values in a `Task#doLast {}`.

**Comment by jjohannes** [comment]
This should not be necessary anymore with the Module support in Gradle 6.4+.
