### ISSUE TITLE
Properly split classpath elements between --module-path & --patch-module

### ISSUE THREAD

**Issue by rgoldberg** [gradle/gradle-java-modules#34]
Must put classpath directories that do not contain a `module-info.class` into correct `--patch-module` instead of into `--module-path`.

This fixes module issues like:

- resources are not found by `Task`s that call `java`, like `JavaExec` & `Test` (#6)
- a task (e.g., `JavaCompile`) compiling a `module-info.java` not seeing classes for packages for that module that were already compiled by a prior task (e.g., Kotlin code compiled by `KotlinCompile`)

**Comment by jjohannes** [comment]
Gradle 6.4 now has Module support built-in. Please open an issue on https://github.com/gradle/gradle if there is still a problem.
