### ISSUE TITLE
Allow main class property to specify --module value in multiple ways

### ISSUE THREAD

**Issue by rgoldberg** [gradle/gradle-java-modules#36]
Allow main class property to specify `--module` value in multiple ways:

1. value is main class; so lookup corresponding module (existing method)
2. value is `<module>/<main class>`, so no lookup necessary
3. value is `<module>`, so expect module to have defined a main-class / MainClass

**Comment by jjohannes** [comment]
The Module support in Gradle 6.4 allows defining the module name in the application plugin extension:

https://docs.gradle.org/6.4-rc-4/userguide/application_plugin.html#sec:application_modular
