### ISSUE TITLE
Tasks that run java should use jar instead of directories in module-path

### ISSUE THREAD

**Issue by rgoldberg** [gradle/gradle-java-modules#38]
Tasks that run java (e.g., `Test`, `JavaExec`) should use jar from `jar` `Task` instead of output directories from `compile*` `Task`s in module-path since:

1. java rejects having a `module-info.class` in a directory on the `--module-path` that exports a package that is supplied from another directory in `--patch-module` (see: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8210151)
2. modules can be created via `META-INF/MANIFEST.MF` or via jar file name

**Comment by jjohannes** [comment]
This is fixed in Gradle 6.4
