### ISSUE TITLE
Chainsaw plugin as a replacement for experimental-jigsaw

### ISSUE THREAD

**Issue by zyxist** [gradle/gradle-java-modules#5]
`experimental-jigsaw` is unusable in more advanced scenarios, e.g. it lacks support for other test engines than JUnit 4, and you can't add additional test libraries, such as Mockito.

This repository seems to be dead, so I reactivated the development of this plugin in my fork: https://github.com/zyxist/chainsaw which has been released to Plugin Portal, and offers additional features.

**Comment by himanshukandwal** [comment]
experimental-jigsaw should also be versioned for Junit5.

https://discuss.gradle.org/t/gradle-java-9-junit-5/24630

**Comment by jjohannes** [comment]
Java Modules are supported directly in Gradle 6.4 now.
